language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
before_install:
  - yarn install
  - npm install --global surge
script:
  - yarn build
deploy:
  provider: surge
  skip_cleanup: true
  domain: rate-nsut.surge.sh
  project: ./build/
on:
  branch: master
after_success:
  - bash ./scripts/deployed.sh